### ISSUE TITLE
[SUGGESTION] GameModes?

### ISSUE THREAD

**Issue by Taki21** [svilex/SkyWars-PocketMine#45]
## Issue description

I play Hypixel Skywars and they offer several gamemodes of skywars:
Normal Insane Team etc... what do u think?

(Insane - Insane modifier and Powerful Items)

**Comment by svilex** [comment]
I think i don't know these gamemodes :confused:
Maybe can you explain better ?

**Comment by TheBigHacker0100** [comment]
Team = some players teaming

**Comment by Taki21** [comment]
So basically:
Solo = this plugin but Insane Solo =
This Plugin + Powerful Items in Chest (Diamond Armor, Potions, enachnted bow, etc.) also + insane Modifier which adds cool stuff like: tnt rain, double health, etc by random!

Team Regular and Insane same idea as Solo regular and insane 

and mega mode:

there needs to be 100 people, then they are divided by 20 so 5 people in each of 20 teams! Mega is considered insane and there is no reg mode for that!

So what do u think?

**Comment by svilex** [comment]
I think i've no time to make all these changes but i will left this issue open , i will make them when i will have time ;)

**Comment by Taki21** [comment]
i can help too :)

**Comment by svilex** [comment]
@Taki21 PRs are welcome

**Comment by KairusDarkSeeker** [comment]
@svilex can I help?

**Comment by svilex** [comment]
@KairusDarkSeeker sure you can

**Comment by KairusDarkSeeker** [comment]
@svilex yas!!!

**Comment by Taki21** [comment]
for team mode the code base will be very similar EXCEPT that the 2 players cant take damage from each other within the team

**Comment by KairusDarkSeeker** [comment]
@Taki21 u mean 3 not 2

**Comment by svilex** [comment]
@KairusDarkSeeker config option for this

**Comment by Taki21** [comment]
team mode is 2 :p

**Comment by KairusDarkSeeker** [comment]
like BrokenLens' team skywars

**Comment by Taki21** [comment]
oh ok :p

**Comment by Taki21** [comment]
config option for 2 or 3 though 3 players should be in mega mode:

at least 60 - 100 people - 3 - 5 people with each of 20 teams

**Comment by KairusDarkSeeker** [comment]
we need mysql support but I'm a noob at SQL :p

**Comment by svilex** [comment]
mysql isn't needed for teams.
what would you save in the database?

We don't care about how many players a team is made, it should be modifiable from the configs

**Comment by KairusDarkSeeker** [comment]
ok

**Comment by BudderSticks** [comment]
could you also add config opinion for teams? because my server does not have 60-100 players yet

**Comment by Taki21** [comment]
thats mega mode for 60-100 people :p 
also @svilex is a sperate branch better or... main?

**Comment by svilex** [comment]
@Taki21 i will create a new branch.

again: i don't care about small, medium, mega, ultra. There will be a config option like `team_players: x`

**Comment by Taki21** [comment]
i know

**Comment by Taki21** [comment]
Mega mode will be excluded since we could just modify the team amount so just team mode will be good. with a config theres no point of mega mode

**Comment by Taki21** [comment]
also, ill try custom config for chest items

**Comment by Taki21** [comment]
i contribute in a SG plugin and they use a method to get the items from config BUt its not so efficient

**Comment by iPeedroPvP** [comment]
add skyshop


Enviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De: Professor Taki <notifications@github.com> Data: 06/09/16  10:56  (GMT-04:00) Para: svilex/SkyWars-PocketMine <SkyWars-PocketMine@noreply.github.com> Assunto: Re: [svilex/SkyWars-PocketMine] [SUGGESTION] GameModes? (#45) 
i contribute in a SG plugin and they use a method to get the items from config BUt its not so efficient

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/svilex/SkyWars-PocketMine","title":"svilex/SkyWars-PocketMine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/svilex/SkyWars-PocketMine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Taki21 in #45: i contribute in a SG plugin and they use a method to get the items from config BUt its not so efficient"}],"action":{"name":"View Issue","url":"https://github.com/svilex/SkyWars-PocketMine/issues/45#issuecomment-244977535"}}}
